[package]
name = "firmware-builder"
authors = ["SIGPwny <hello@sigpwny.com>"]
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
common = { path = "../common" }
rand = "0.9.0"
serde = "1.0.217"
serde_json = "1.0.138"
