[package]
name = "firmware-builder"
authors = ["SIGPwny <hello@sigpwny.com>"]
edition = "2021"
publish = false

[dependencies]
common = { path = "../common", features = ["std"] }
rand = "0.9.0"
serde = "1.0.217"
serde_json = "1.0.138"
