// Primitives
pub const LEN_CHANNEL_ID: usize = 4;
pub const LEN_TIMESTAMP: usize = 8;

pub const LEN_RNG_SEED: usize = 64;

// Ascon constants
pub const LEN_ASCON_KEY: usize = 16;
pub const LEN_ASCON_NONCE: usize = 16;
pub const LEN_ASCON_TAG: usize = 16;
pub const LEN_ASCON_AEAD_OVERHEAD: usize = LEN_ASCON_NONCE + LEN_ASCON_TAG;

// Secrets constants
pub const LEN_BASE_CHANNEL_SECRET: usize = 32;
pub const LEN_BASE_SUBSCRIPTION_SECRET: usize = 32;
pub const LEN_CHANNEL_SECRET: usize = 32;

// Update subscription constants
pub const LEN_SUBSCRIPTION_INFO: usize = LEN_CHANNEL_ID + 2 * LEN_TIMESTAMP;
pub const LEN_STORED_SUBSCRIPTION: usize = LEN_SUBSCRIPTION_INFO + LEN_CHANNEL_SECRET;
pub const LEN_ENCRYPTED_SUBSCRIPTION: usize = LEN_STORED_SUBSCRIPTION + LEN_ASCON_AEAD_OVERHEAD;

// List subscription constants
pub const EMERGENCY_CHANNEL_ID: u32 = 0x0;
pub const LEN_STANDARD_CHANNELS: usize = 8;
pub const LEN_SUBSCRIPTION_INFO_LIST: usize = 4 + LEN_STANDARD_CHANNELS * LEN_SUBSCRIPTION_INFO; // The 4 accounts for the 32-bit "number of channels" requirement in host tools

// Frame and picture constants
pub const LEN_PICTURE_LEN: usize = 1;
pub const MAX_LEN_PICTURE: usize = 64;
pub const LEN_ENCRYPTED_PICTURE: usize = MAX_LEN_PICTURE + LEN_ASCON_AEAD_OVERHEAD;
pub const LEN_DECRYPTED_FRAME: usize =
    LEN_ENCRYPTED_PICTURE + LEN_CHANNEL_ID + LEN_TIMESTAMP + LEN_PICTURE_LEN;
pub const LEN_ENCRYPTED_FRAME: usize = LEN_DECRYPTED_FRAME + LEN_ASCON_AEAD_OVERHEAD;

// Flash constants
pub const FLASH_PAGE_SIZE: u32 = 0x2000;
pub const FLASH_ADDR_BASE: u32 = 0x1000_E000;
pub const FLASH_FIRMWARE_SIZE: u32 = 28 * FLASH_PAGE_SIZE;
pub const FLASH_FIRMWARE_CODE_SIZE: u32 = 25 * FLASH_PAGE_SIZE;

pub const FLASH_OFFSET_RANDOM_BYTES: u32 = 25 * FLASH_PAGE_SIZE;
pub const FLASH_OFFSET_FRAME_KEY: u32 = 26 * FLASH_PAGE_SIZE;
pub const FLASH_OFFSET_SUBSCRIPTION_KEY: u32 = FLASH_OFFSET_FRAME_KEY + LEN_ASCON_KEY as u32;
pub const FLASH_OFFSET_SUBSCRIPTION_BASE: u32 = 27 * FLASH_PAGE_SIZE;

pub const FLASH_MAGIC_SUBSCRIPTION: u8 = 0x53;

pub const FLASH_ADDR_RANDOM_BYTES: u32 = FLASH_ADDR_BASE + FLASH_OFFSET_RANDOM_BYTES;
pub const FLASH_ADDR_FRAME_KEY: u32 = FLASH_ADDR_BASE + FLASH_OFFSET_FRAME_KEY;
pub const FLASH_ADDR_SUBSCRIPTION_KEY: u32 = FLASH_ADDR_BASE + FLASH_OFFSET_SUBSCRIPTION_KEY;
pub const FLASH_ADDR_SUBSCRIPTION_BASE: u32 = FLASH_ADDR_BASE + FLASH_OFFSET_SUBSCRIPTION_BASE;
