[config]
skip_core_tasks = true

[tasks.default]
alias = "release-flow"

[tasks.docker-flow]
description = "Builds the decoder within Docker using the expected input and output mounts (/global.secrets, /out)."
dependencies = [
  "pre-docker",
  "release-flow",
  "post-docker"
]

[tasks.clean-docker]
command = "rm"
args = ["-f", "max78000/global.secrets", "/out/max78000.bin"]

[tasks.pre-docker]
dependencies = ["clean-docker"]
command = "cp"
args = ["/global.secrets", "max78000/global.secrets"]

[tasks.post-docker]
command = "cp"
args = ["firmware-builder/out/max78000.bin", "/out/max78000.bin"]

[tasks.release-flow]
description = "Full production build"
dependencies = [
  { name = "build-release-flow", path = "max78000/Makefile.toml" },
  { name = "build-firmware", path = "firmware-builder/Makefile.toml" },
]