[package]
name = "common"
version = "0.1.0"
authors = ["SIGPwny <hello@sigpwny.com>"]
edition = "2021"
publish = false

# TODO
[package.metadata.docs.rs]
targets = ["thumbv7em-none-eabihf"]

[dependencies]
