[config]
skip_core_tasks = true

[tasks.default]
alias = "build-release-flow"

[tasks.build-release-flow]
dependencies = ["clean", "build-release"]

[tasks.build-release]
description = "Full production build"
command = "cargo"
# args = ["build", "--release"]
args = ["objcopy", "--release", "--", "-O", "binary", "./out/decoder.bin"]

[tasks.build-dev]
description = "Full development build"
command = "cargo"
args = ["build --dev"]

[tasks.clean]
script_runner = "@shell"
script = "rm -f ./out/decoder.bin"