[config]
skip_core_tasks = true

[tasks.default]
alias = "build-release-flow"

[tasks.build-release-flow]
dependencies = ["build-release"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-release]
description = "Full production build"
command = "cargo"
# args = ["build", "--release"]
args = ["objcopy", "--release", "--", "-O", "binary", "./out/max78000.bin"]

[tasks.build-dev]
description = "Full development build"
command = "cargo"
args = ["build --dev"]